[package]
name          = "mini-lsm"
version       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
publish       = false

[dependencies]
anyhow              = { workspace = true }
arc-swap            = { workspace = true }
bytes               = { workspace = true }
clap                = { workspace = true }
console             = { workspace = true }
crossbeam-epoch     = { workspace = true }
crossbeam-skiplist  = { workspace = true }
crossbeam-channel   = { workspace = true }
duct                = { workspace = true }
farmhash            = { workspace = true }
moka                = { workspace = true }
nom                 = { workspace = true }
ouroboros           = { workspace = true }
parking_lot         = { workspace = true }
rand                = { workspace = true }
rustyline           = { workspace = true }
serde               = { workspace = true }
serde_json          = { workspace = true }
